# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus-p"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.50.4:8080']